# -*- coding: utf-8 -*-
"""Variable tranformation and deletion .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v2qzRTcFph8Qir6NTKB2wtSHtztMUTIv
"""

import numpy as np
import pandas as pd
import seaborn as sns

df = pd.read_csv('/content/drive/MyDrive/House_Price[1].csv',header = 0)

df.info()

sns.jointplot(x='crime_rate', y = 'price',data = df)

df.crime_rate = np.log(1 + df.crime_rate)

sns.jointplot(x='crime_rate', y = 'price',data = df)

df['avg_dist'] = (df.dist1 + df.dist2 + df.dist3 + df.dist4)/4

df.head()

del df["dist1"]

del df["dist2"]

del df["dist3"]

del df["dist4"]

df.head()

del df["bus_ter"]

df.head()

"""# **dummy variable creation**"""

df = pd.get_dummies(df)

df.head()

del df["airport_NO"]

del df["waterbody_None"]

df.head()

"""Coorelation analysis in python

"""

df.corr()

del df["parks"]

df.head()

import statsmodels.api as sn

X = sn.add_constant(df['room_num'])

lm = sn.OLS(df['price'],X).fit()

lm.summary()

from sklearn.linear_model import LinearRegression

y = df['price']

X = df[['room_num']]

lm2 = LinearRegression()

lm2.fit(X,y)

print(lm2.intercept_,lm2.coef_)

lm2.predict(X)

help(sns.jointplot)

sns.jointplot(x = df['room_num'] , y = df['price'] , data = df , kind = 'reg')

X_multi = df.drop("price",axis = 1)

X_multi.head()

y_multi = df["price"]

y_multi.head()

X_multi_cons = sn.add_constant(X_multi)

X_multi_cons.head()